import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SiteHeader } from "@/components/header/site-header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ashutosh Gaurav",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="author" content="Ashutosh Gaurav" />
        <meta
          name="Keywords"
          content="Ashutosh, Ashutosh Gaurav, Ashutosh Rana, AshutoshGaurav05, HTML, CSS, JavaScript, Python, Java, MySQL, Icons, NodeJS, React, AI, Git, GitHub, Data Science, Programming, Web Development, Learning, Quiz, Courses, Lessons, References, Examples, Learn to code, Source code, Tips, Website,  Web-App"
        />
        <meta
          name="copyright"
          content="Copyright © 2024 Ashutosh Gaurav All Rights Reserved."
        />
        <meta name="robots" content="index, follow" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Ashutosh Gaurav" />
        <meta property="og:title" content="Ashutosh Gaurav" />
        <meta
          property="og:description"
          content="Ashutosh Gaurav - Web Developer, Programmer, Designer, Learner, and Explorer."
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

/*
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
*/
